// Mocks generated by Mockito 5.4.4 from annotations
// in blog_posts_challenge/test/feature/blog/data/repositories/post_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:blog_posts_challenge/core/common/models/http_response_model.dart'
    as _i2;
import 'package:blog_posts_challenge/feature/blog/data/data_source/post_data_source.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHttpResponseModel_0 extends _i1.SmartFake
    implements _i2.HttpResponseModel {
  _FakeHttpResponseModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PostDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostDataSource extends _i1.Mock implements _i3.PostDataSource {
  MockPostDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.HttpResponseModel> getAllPosts() => (super.noSuchMethod(
        Invocation.method(
          #getAllPosts,
          [],
        ),
        returnValue:
            _i4.Future<_i2.HttpResponseModel>.value(_FakeHttpResponseModel_0(
          this,
          Invocation.method(
            #getAllPosts,
            [],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponseModel>);
}
